spring:
  application:
    name: authService
  datasource:
    url: jdbc:postgresql://localhost:5432/tracker
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8082